---
# Source: helm for kubernetes/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-88594ebc                  # Ingress name
  labels:
    app: backend-88594ebc
spec:
  ingressClassName: nginx   # Optional ingressClass
  rules:
    - host: "backend-88594ebc.smartops.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-88594ebc               # Links to Service name dynamically
                port:
                  number: 3000  # Links to service port dynamically
